from sqlalchemy.orm import Session
from backend.models.lake import LakeModel
from backend.models.alert import AlertModel

INITIAL_LAKES = [
    {
        "id": "gl-00124",
        "node_id": "SL-22-ALPHA",
        "name": "South Lhonak Lake",
        "basin": "Teesta Basin",
        "state": "Sikkim",
        "lat": 27.9158,
        "lng": 88.5822,
        "risk_score": 94.2,
        "tier": "critical",
        "vulnerable_pop": 12450,
        "last_updated": "2023-11-24T14:02:00Z",
        "watch_id": "IND-SK-0042",
        "predictions": {"h72": 64, "h24": 82, "h6": 94},
        "telemetry": {"waterLevelMPerHr": 1.2, "seismicMag": 3.2, "areaDeltaPct": 12},
        "shap": [
            {"feature": "PRECIP", "value": 0.14, "direction": "up"},
            {"feature": "TEMP", "value": 0.09, "direction": "up"},
            {"feature": "STRESS", "value": -0.03, "direction": "down"},
        ],
        "flood_projection": [
            {"timeBand": "04:15:00", "village": "Chungthang", "popAtRisk": 1240, "urgency": "critical"},
            {"timeBand": "06:45:00", "village": "Lachen", "popAtRisk": 890, "urgency": "elevated"},
            {"timeBand": "09:30:00", "village": "Mangan", "popAtRisk": 3400, "urgency": "watch"},
        ],
        "escalation_level": 4,
        "sms_sent": 142,
    },
    {
        "id": "gl-00452",
        "node_id": "GG-08-BETA",
        "name": "Ghepan Ghat",
        "basin": "Chenab Basin",
        "state": "Himachal Pradesh",
        "lat": 32.45,
        "lng": 77.32,
        "risk_score": 12.4,
        "tier": "safe",
        "vulnerable_pop": 450,
        "last_updated": "2023-11-24T10:00:00Z",
        "watch_id": "IND-HP-0091",
        "predictions": {"h72": 38, "h24": 41, "h6": 44},
        "telemetry": {"waterLevelMPerHr": 0.1, "seismicMag": 2.1, "areaDeltaPct": 2},
        "shap": [
            {"feature": "PRECIP", "value": 0.04, "direction": "up"},
            {"feature": "TEMP", "value": -0.02, "direction": "down"},
            {"feature": "STRESS", "value": 0.01, "direction": "up"},
        ],
        "flood_projection": [
            {"timeBand": "12:00:00", "village": "Udaipur", "popAtRisk": 120, "urgency": "watch"}
        ],
        "escalation_level": 1,
        "sms_sent": 0,
    },
    {
        "id": "gl-ct-12",
        "node_id": "CT-12-DELTA",
        "name": "Chandra Tal",
        "basin": "Chandra",
        "state": "Himachal Pradesh",
        "lat": 32.48,
        "lng": 77.62,
        "risk_score": 12.0,
        "tier": "safe",
        "vulnerable_pop": 80,
        "last_updated": "2023-11-24T09:12:00Z",
        "watch_id": "IND-HP-0102",
        "predictions": {"h72": 11, "h24": 13, "h6": 14},
        "telemetry": {"waterLevelMPerHr": 0.02, "seismicMag": 1.2, "areaDeltaPct": 0.5},
        "shap": [
            {"feature": "PRECIP", "value": -0.01, "direction": "down"},
            {"feature": "TEMP", "value": 0.01, "direction": "up"},
            {"feature": "STRESS", "value": 0, "direction": "up"},
        ],
        "flood_projection": [],
        "escalation_level": 0,
        "sms_sent": 0,
    },
    {
        "id": "gl-00089",
        "node_id": "GL-00089",
        "name": "Imja Tsho",
        "basin": "Dudh Koshi",
        "state": "Nepal",
        "lat": 27.9,
        "lng": 86.93,
        "risk_score": 78.5,
        "tier": "high",
        "vulnerable_pop": 8200,
        "last_updated": "2023-11-24T13:45:00Z",
        "watch_id": "NPL-KH-0021",
        "predictions": {"h72": 70, "h24": 76, "h6": 80},
        "telemetry": {"waterLevelMPerHr": 0.4, "seismicMag": 2.8, "areaDeltaPct": 4},
        "shap": [
            {"feature": "PRECIP", "value": 0.08, "direction": "up"},
            {"feature": "TEMP", "value": 0.05, "direction": "up"},
            {"feature": "STRESS", "value": -0.01, "direction": "down"},
        ],
        "flood_projection": [
            {"timeBand": "18:00:00", "village": "Dingboche", "popAtRisk": 400, "urgency": "elevated"}
        ],
        "escalation_level": 3,
        "sms_sent": 1240,
    },
    {
        "id": "gl-00215",
        "node_id": "GL-00215",
        "name": "Tsho Rolpa",
        "basin": "Tama Koshi",
        "state": "Nepal",
        "lat": 28.05,
        "lng": 86.47,
        "risk_score": 42.1,
        "tier": "advisory",
        "vulnerable_pop": 6100,
        "last_updated": "2023-11-24T12:30:00Z",
        "watch_id": "NPL-DH-0088",
        "predictions": {"h72": 40, "h24": 43, "h6": 45},
        "telemetry": {"waterLevelMPerHr": 0.15, "seismicMag": 2.0, "areaDeltaPct": 1.5},
        "shap": [
            {"feature": "PRECIP", "value": 0.03, "direction": "up"},
            {"feature": "TEMP", "value": 0.02, "direction": "up"},
            {"feature": "STRESS", "value": 0, "direction": "up"},
        ],
        "flood_projection": [],
        "escalation_level": 1,
        "sms_sent": 0,
    },
    {
        "id": "gl-00331",
        "node_id": "GL-00331",
        "name": "Pareechu Lake",
        "basin": "Sutlej Basin",
        "state": "Himachal Pradesh",
        "lat": 31.52,
        "lng": 78.38,
        "risk_score": 89.9,
        "tier": "critical",
        "vulnerable_pop": 15700,
        "last_updated": "2023-11-24T14:15:00Z",
        "watch_id": "IND-HP-0140",
        "predictions": {"h72": 72, "h24": 85, "h6": 91},
        "telemetry": {"waterLevelMPerHr": 0.9, "seismicMag": 2.9, "areaDeltaPct": 8},
        "shap": [
            {"feature": "PRECIP", "value": 0.12, "direction": "up"},
            {"feature": "TEMP", "value": 0.07, "direction": "up"},
            {"feature": "STRESS", "value": -0.04, "direction": "down"},
        ],
        "flood_projection": [
            {"timeBand": "07:30:00", "village": "Rampur", "popAtRisk": 2100, "urgency": "critical"}
        ],
        "escalation_level": 4,
        "sms_sent": 8922,
    },
    {
        "id": "gl-00501",
        "node_id": "SH-01-KARAKORAM",
        "name": "Shishper Lake",
        "basin": "Hunza Basin",
        "state": "Gilgit-Baltistan",
        "lat": 36.4360,
        "lng": 74.6020,
        "risk_score": 92.4,
        "tier": "critical",
        "vulnerable_pop": 8500,
        "last_updated": "2026-09-14T08:00:00Z",
        "watch_id": "KK-HZ-0015",
        "predictions": {"h72": 78, "h24": 88, "h6": 94},
        "telemetry": {"waterLevelMPerHr": 1.45, "seismicMag": 2.6, "areaDeltaPct": 18.5},
        "shap": [
            {"feature": "STRESS", "value": 0.22, "direction": "up"},
            {"feature": "TEMP", "value": 0.14, "direction": "up"},
            {"feature": "PRECIP", "value": 0.05, "direction": "up"},
        ],
        "flood_projection": [
            {"timeBand": "01:15:00", "village": "Hassanabad", "popAtRisk": 2100, "urgency": "critical"},
            {"timeBand": "02:30:00", "village": "Aliabad", "popAtRisk": 4200, "urgency": "elevated"},
        ],
        "escalation_level": 4,
        "sms_sent": 3400,
    },
    {
        "id": "gl-00502",
        "node_id": "CH-02-GARHWAL",
        "name": "Chorabari Tal (Gandhi Sarovar)",
        "basin": "Mandakini Basin",
        "state": "Uttarakhand",
        "lat": 30.7480,
        "lng": 79.0620,
        "risk_score": 79.8,
        "tier": "high",
        "vulnerable_pop": 14200,
        "last_updated": "2026-09-14T10:30:00Z",
        "watch_id": "IND-UK-0055",
        "predictions": {"h72": 65, "h24": 74, "h6": 82},
        "telemetry": {"waterLevelMPerHr": 0.85, "seismicMag": 3.1, "areaDeltaPct": 6.4},
        "shap": [
            {"feature": "PRECIP", "value": 0.18, "direction": "up"},
            {"feature": "STRESS", "value": 0.09, "direction": "up"},
            {"feature": "TEMP", "value": 0.04, "direction": "up"},
        ],
        "flood_projection": [
            {"timeBand": "00:45:00", "village": "Kedarnath Town", "popAtRisk": 3800, "urgency": "critical"},
            {"timeBand": "02:15:00", "village": "Rambara", "popAtRisk": 1200, "urgency": "critical"},
            {"timeBand": "04:30:00", "village": "Gaurikund", "popAtRisk": 4500, "urgency": "elevated"},
        ],
        "escalation_level": 3,
        "sms_sent": 1850,
    },
    {
        "id": "gl-00503",
        "node_id": "GY-03-LADAKH",
        "name": "Gya Lake",
        "basin": "Indus Basin",
        "state": "Ladakh",
        "lat": 33.6500,
        "lng": 77.7300,
        "risk_score": 46.5,
        "tier": "advisory",
        "vulnerable_pop": 1150,
        "last_updated": "2026-09-14T06:15:00Z",
        "watch_id": "IND-LD-0012",
        "predictions": {"h72": 35, "h24": 42, "h6": 48},
        "telemetry": {"waterLevelMPerHr": 0.32, "seismicMag": 3.8, "areaDeltaPct": -2.1},
        "shap": [
            {"feature": "STRESS", "value": 0.11, "direction": "up"},
            {"feature": "TEMP", "value": 0.06, "direction": "up"},
            {"feature": "PRECIP", "value": -0.02, "direction": "down"},
        ],
        "flood_projection": [
            {"timeBand": "01:30:00", "village": "Gya Village", "popAtRisk": 650, "urgency": "elevated"},
            {"timeBand": "03:00:00", "village": "Miru", "popAtRisk": 500, "urgency": "watch"},
        ],
        "escalation_level": 2,
        "sms_sent": 420,
    },
    {
        "id": "gl-00504",
        "node_id": "TH-04-LUNANA",
        "name": "Thorthormi Lake Complex",
        "basin": "Puna Tsang Chhu",
        "state": "Bhutan",
        "lat": 28.1620,
        "lng": 90.2480,
        "risk_score": 88.1,
        "tier": "critical",
        "vulnerable_pop": 18900,
        "last_updated": "2026-09-14T11:00:00Z",
        "watch_id": "BTN-LN-0007",
        "predictions": {"h72": 72, "h24": 84, "h6": 90},
        "telemetry": {"waterLevelMPerHr": 1.10, "seismicMag": 2.4, "areaDeltaPct": 14.8},
        "shap": [
            {"feature": "STRESS", "value": 0.19, "direction": "up"},
            {"feature": "TEMP", "value": 0.12, "direction": "up"},
            {"feature": "PRECIP", "value": 0.08, "direction": "up"},
        ],
        "flood_projection": [
            {"timeBand": "03:00:00", "village": "Thanza", "popAtRisk": 920, "urgency": "critical"},
            {"timeBand": "07:30:00", "village": "Punakha", "popAtRisk": 9500, "urgency": "critical"},
        ],
        "escalation_level": 4,
        "sms_sent": 5200,
    },
    {
        "id": "gl-00505",
        "node_id": "RT-05-SIKKIM",
        "name": "Rathong Lake",
        "basin": "Rangit Basin",
        "state": "Sikkim",
        "lat": 27.5620,
        "lng": 88.1650,
        "risk_score": 74.2,
        "tier": "high",
        "vulnerable_pop": 9600,
        "last_updated": "2026-09-14T09:45:00Z",
        "watch_id": "IND-SK-0089",
        "predictions": {"h72": 58, "h24": 70, "h6": 77},
        "telemetry": {"waterLevelMPerHr": 0.68, "seismicMag": 2.7, "areaDeltaPct": 5.8},
        "shap": [
            {"feature": "PRECIP", "value": 0.15, "direction": "up"},
            {"feature": "STRESS", "value": 0.08, "direction": "up"},
            {"feature": "TEMP", "value": 0.05, "direction": "up"},
        ],
        "flood_projection": [
            {"timeBand": "02:00:00", "village": "Dzongri Snout", "popAtRisk": 240, "urgency": "elevated"},
            {"timeBand": "05:30:00", "village": "Yuksom", "popAtRisk": 3200, "urgency": "elevated"},
        ],
        "escalation_level": 3,
        "sms_sent": 1100,
    },
    {
        "id": "gl-00506",
        "node_id": "BC-06-PIRPANJAL",
        "name": "Bramsar-Chirsar Twin Lakes",
        "basin": "Veshav Basin",
        "state": "Jammu & Kashmir",
        "lat": 33.5850,
        "lng": 74.8350,
        "risk_score": 38.4,
        "tier": "advisory",
        "vulnerable_pop": 7400,
        "last_updated": "2026-09-14T07:20:00Z",
        "watch_id": "IND-JK-0112",
        "predictions": {"h72": 28, "h24": 34, "h6": 40},
        "telemetry": {"waterLevelMPerHr": 0.22, "seismicMag": 2.2, "areaDeltaPct": 1.8},
        "shap": [
            {"feature": "PRECIP", "value": 0.07, "direction": "up"},
            {"feature": "TEMP", "value": 0.03, "direction": "up"},
            {"feature": "STRESS", "value": -0.01, "direction": "down"},
        ],
        "flood_projection": [
            {"timeBand": "02:30:00", "village": "Aharbal", "popAtRisk": 1400, "urgency": "elevated"},
            {"timeBand": "05:00:00", "village": "Kulgam Town", "popAtRisk": 6000, "urgency": "watch"},
        ],
        "escalation_level": 1,
        "sms_sent": 150,
    },
    {
        "id": "gl-00507",
        "node_id": "BG-07-PIRPANJAL",
        "name": "Bhagsar Lake",
        "basin": "Poonch Basin",
        "state": "Jammu & Kashmir",
        "lat": 33.5420,
        "lng": 74.5280,
        "risk_score": 18.6,
        "tier": "safe",
        "vulnerable_pop": 2800,
        "last_updated": "2026-09-14T06:40:00Z",
        "watch_id": "IND-JK-0119",
        "predictions": {"h72": 15, "h24": 18, "h6": 20},
        "telemetry": {"waterLevelMPerHr": 0.05, "seismicMag": 1.8, "areaDeltaPct": 0.4},
        "shap": [
            {"feature": "TEMP", "value": 0.02, "direction": "up"},
            {"feature": "PRECIP", "value": 0.01, "direction": "up"},
            {"feature": "STRESS", "value": -0.02, "direction": "down"},
        ],
        "flood_projection": [
            {"timeBand": "04:00:00", "village": "Bafliaz", "popAtRisk": 800, "urgency": "watch"},
        ],
        "escalation_level": 0,
        "sms_sent": 0,
    },
    {
        "id": "gl-00508",
        "node_id": "NG-08-HARMUKH",
        "name": "Nundkol-Gangabal Complex",
        "basin": "Sind Basin",
        "state": "Jammu & Kashmir",
        "lat": 34.4280,
        "lng": 74.9250,
        "risk_score": 44.7,
        "tier": "advisory",
        "vulnerable_pop": 12800,
        "last_updated": "2026-09-14T08:50:00Z",
        "watch_id": "IND-JK-0074",
        "predictions": {"h72": 36, "h24": 42, "h6": 46},
        "telemetry": {"waterLevelMPerHr": 0.35, "seismicMag": 2.5, "areaDeltaPct": 2.6},
        "shap": [
            {"feature": "TEMP", "value": 0.08, "direction": "up"},
            {"feature": "PRECIP", "value": 0.05, "direction": "up"},
            {"feature": "STRESS", "value": 0.02, "direction": "up"},
        ],
        "flood_projection": [
            {"timeBand": "02:45:00", "village": "Naranag", "popAtRisk": 1100, "urgency": "elevated"},
            {"timeBand": "06:00:00", "village": "Kangan / USHP Hydel", "popAtRisk": 6200, "urgency": "elevated"},
        ],
        "escalation_level": 2,
        "sms_sent": 650,
    },
]

INITIAL_ALERTS = [
    {
        "id": "a1",
        "ts": "2023-11-24T14:22:08Z",
        "severity": "critical",
        "lake_name": "South Lhonak Lake",
        "lake_id": "gl-00124",
        "sms_count": 4812,
        "channels": ["SDMA", "NDRF", "Panchayat-V"],
        "status": "pending",
    },
    {
        "id": "a2",
        "ts": "2023-11-24T09:15:33Z",
        "severity": "high",
        "lake_name": "Imja Tsho",
        "lake_id": "gl-00089",
        "sms_count": 1240,
        "channels": ["SDMA", "Panchayat-B"],
        "status": "ack",
    },
    {
        "id": "a3",
        "ts": "2023-11-23T21:04:12Z",
        "severity": "advisory",
        "lake_name": "Tsho Rolpa",
        "lake_id": "gl-00215",
        "sms_count": 0,
        "channels": ["SDMA-INTERNAL"],
        "status": "ack",
    },
    {
        "id": "a4",
        "ts": "2023-11-23T04:44:59Z",
        "severity": "critical",
        "lake_name": "Gyalzen Peak Node",
        "lake_id": "gl-00331",
        "sms_count": 8922,
        "channels": ["SDMA", "NDRF", "DCC-ALL"],
        "status": "ack",
    },
    {
        "id": "a5",
        "ts": "2026-09-14T08:15:00Z",
        "severity": "critical",
        "lake_name": "Shishper Lake",
        "lake_id": "gl-00501",
        "sms_count": 3400,
        "channels": ["SDMA", "NDMA-PAK", "KKH-CONTROL"],
        "status": "pending",
    },
    {
        "id": "a6",
        "ts": "2026-09-14T10:45:00Z",
        "severity": "high",
        "lake_name": "Chorabari Tal (Gandhi Sarovar)",
        "lake_id": "gl-00502",
        "sms_count": 1850,
        "channels": ["USDMA", "NDRF", "BKTC"],
        "status": "ack",
    },
    {
        "id": "a7",
        "ts": "2026-09-14T11:15:00Z",
        "severity": "critical",
        "lake_name": "Thorthormi Lake Complex",
        "lake_id": "gl-00504",
        "sms_count": 5200,
        "channels": ["DDM-BHUTAN", "DHMS"],
        "status": "pending",
    },
    {
        "id": "a8",
        "ts": "2026-09-14T09:00:00Z",
        "severity": "advisory",
        "lake_name": "Nundkol-Gangabal Complex",
        "lake_id": "gl-00508",
        "sms_count": 650,
        "channels": ["JKSDMA", "PDC-SIND"],
        "status": "ack",
    },
]

def seed_database(db: Session):
    """Populates or idempotently upserts lakes and alerts."""
    existing_ids = {row[0] for row in db.query(LakeModel.id).all()}
    new_lakes = 0
    for lake_data in INITIAL_LAKES:
        if lake_data["id"] not in existing_ids:
            db.add(LakeModel(**lake_data))
            new_lakes += 1
    if new_lakes:
        db.commit()

    existing_alert_ids = {row[0] for row in db.query(AlertModel.id).all()}
    new_alerts = 0
    for alert_data in INITIAL_ALERTS:
        if alert_data["id"] not in existing_alert_ids:
            db.add(AlertModel(**alert_data))
            new_alerts += 1
    if new_alerts:
        db.commit()
